# Generated by Django 4.2.1 on 2023-06-01 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_element_inserted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='user',
        ),
        migrations.AddField(
            model_name='entity',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
