# Generated by Django 4.2.1 on 2023-06-05 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_entity_iss_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='iss_private',
            new_name='is_private',
        ),
    ]
