# Generated by Django 4.2.1 on 2023-06-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_entity_user_entity_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='user',
            new_name='users',
        ),
    ]
