# Generated by Django 4.1.5 on 2023-06-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_entity_share_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
    ]
