# Generated by Django 4.2.1 on 2023-06-07 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_element_access_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_entities', to=settings.AUTH_USER_MODEL),
        ),
    ]
