# Generated by Django 4.2.1 on 2023-06-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_element_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='share_link',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
