# Generated by Django 4.2.2 on 2023-07-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_entity_latitude_entity_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
